import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "@/app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { WhatsAppFloat } from "@/components/whatsapp/WhatsAppFloat";
import { LanguageProvider } from "@/context/LanguageContext";
import { Toaster } from "react-hot-toast";
import "react-datepicker/dist/react-datepicker.css"; // <-- important, global import
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bayyitni",
  description: "Generated by Bayyitni devs team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <ClerkProvider afterSignOutUrl="/">
        <AuthProvider>
          <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} bg-background`}
          >
            <LanguageProvider>
              {children}
              <WhatsAppFloat />
            </LanguageProvider>
            <Toaster position="top-right" reverseOrder={false} />
          </body>
        </AuthProvider>
      </ClerkProvider>
    </html>
  );
}
